title: Mitchell Peters
description: Software Engineer

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


author:
  name             : "Mitchell Peters"
  bio              : 
  location         : "Michigan, US"
  employer         : "The Kendall Group"
  pubmed           : 
  email            : "petemitc at stu dot gvsu dot edu"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  foursquare       :
  github           : "mppeters"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : 
  lastfm           : 
  linkedin         : "mitch-peterscs"
  orcid            : 
  pinterest        :
  soundcloud       :
  stackoverflow    : 
  steam            :
  tumblr           :
  twitter          : 
  vine             :
  weibo            :
  xing             :
  youtube          : 
  wikipedia        :
